print( "Create a student profile!")

name = input("What is your name?\n>> ")
age = input("How old are you?\n>> ")
hometown = input("Where is your home residense?\n>> ")
fav_food = input("What is your favorite food?\n>> ")
fav_hobby = input("What is your favorite hobby?\n>> ")
skill_learn = input("What skill do you want to learn?\n>> ")
dream_job = input("What is your dream job?\n>> ")
vist = input("Where would you like to visit?\n>> ")
         
grade = input("What grade are you in (number st/nd/th)?\n>> ")
school = input("What school do you go to?\n>> ")
grad_year = input("What year did/do you graduate\n>> ")
study_time = input("How many hours do you study?\n>> ")
fav_subject = input("What is your favorite school subject?\n>> ")
school_goal = input("What is your goal in school?\n>> ")
